# Generated by Django 6.0.4 on 2026-04-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_turfblogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='About Us', max_length=255)),
                ('about_content', models.TextField(default='Default about content...')),
                ('contact_address', models.CharField(default='Our Address', max_length=500)),
                ('contact_phone', models.CharField(default='+91 0000000000', max_length=20)),
                ('contact_email', models.EmailField(default='info@example.com', max_length=254)),
                ('homepage_banner_title', models.CharField(default='Best Synthetic Turf in the City', max_length=255)),
                ('homepage_banner_subtitle', models.CharField(default='Enjoy your Play ground', max_length=255)),
            ],
        ),
    ]
