# Generated by Django 6.0.4 on 2026-04-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='TimeSlot',
            field=models.CharField(choices=[('12-01 AM', '12-01 AM'), ('01-02 AM', '01-02 AM'), ('02-03 AM', '02-03 AM'), ('03-04 AM', '03-04 AM'), ('04-05 AM', '04-05 AM'), ('05-06 AM', '05-06 AM'), ('06-07 AM', '06-07 AM'), ('07-08 AM', '07-08 AM'), ('08-09 AM', '08-09 AM'), ('09-10 AM', '09-10 AM'), ('10-11 AM', '10-11 AM'), ('11-12 AM', '11-12 AM'), ('12-01 PM', '12-01 PM'), ('01-02 PM', '01-02 PM'), ('02-03 PM', '02-03 PM'), ('03-04 PM', '03-04 PM'), ('04-05 PM', '04-05 PM'), ('05-06 PM', '05-06 PM'), ('06-07 PM', '06-07 PM'), ('07-08 PM', '07-08 PM'), ('08-09 PM', '08-09 PM'), ('09-10 PM', '09-10 PM'), ('10-11 PM', '10-11 PM'), ('11-12 PM', '11-12 PM')], max_length=255),
        ),
        migrations.AlterField(
            model_name='turfdetails',
            name='Turf_price',
            field=models.IntegerField(),
        ),
    ]
