# Generated by Django 6.0.4 on 2026-04-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_timeslot_timeslot_alter_turfdetails_turf_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(default='https://facebook.com', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(default='Premium multi-sport facilities designed for elite performance. Book your session and dominate the pitch.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(default='https://instagram.com', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='operating_hours',
            field=models.CharField(default='08.00AM - 10.00PM', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='BOOKTURF PRO', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(default='https://twitter.com', max_length=500),
        ),
    ]
